### ISSUE TITLE
Digits grouping is not supported

### ISSUE THREAD

**Issue by intrueder** [mr-jonix/kottans#1]
"5105105105105100" - Pass
"5105 1051 0510 5100" - Fail

**Comment by mr-jonix** [comment]
![image](https://cloud.githubusercontent.com/assets/9006107/15056451/51139370-131a-11e6-8e3d-d1f8630fcf9f.png)

cannot replicate issue.

**Comment by intrueder** [comment]
This particular issue was fixed with commit 98b814ac4832fc06432c61580efe2905006cd4e5
